### DISCUSSION TITLE
Piotec Tracker, how to handle?

### DISCUSSION THREAD

**Discussion by Stev-G** [ChristopheHD/HA_enoceanmqtt-addon#32] [General]
Hello,

first many thanks for the great work. The old one was not usable anymore on Raspi5. I am not sure, if I am right to ask you. I have a Piotec Tracker, which allows to send every 30s a message, that the tracker is available with the EEP 0xA5, 0x07, 0x01. With the same adress the tracker sends, if a button is pressed, the message via the EEP 0xF6, 0x01, 0x01.

https://www.piotek.de/?a=389&lang=eng

https://www.eltako.com/fileadmin/downloads/en/_bedienung/FTTB_30100018_1_gb.pdf

Inside of the enocean receiving part it seems to work if I put both into the *.devie file, as you can see in the following log of the HA_Enocean_Addon.

2025-04-10 18:08:47,058 DEBUG: XX:XX:XX:XX->FF:FF:FF:FF (-54 dBm): 0x01 ['0xf6', '0x70', '0x1', '0xa7', '0x4c', '0x69', '0x30'] ['0x1', '0xff', '0xff', '0xff', '0xff', '0x36', '0x0'] OrderedDict()
2025-04-10 18:08:47,059 DEBUG: enoceanmqtt/FB/XXXX: PB (Status of the push button)=Pressed
2025-04-10 18:08:47,060 DEBUG: enoceanmqtt/FB/XXXX: Sent MQTT: {"RSSI": -54, "DATE": "2025-04-10T18:08:47.058815", "RAW_DATA": "70:30", "PB": 1}
2025-04-10 18:08:47,060 DEBUG: Sending PUBLISH (d0, q0, r1, m236), 'b'enoceanmqtt/FB/XXXX'', ... (87 bytes)
2025-04-10 18:08:47,218 DEBUG: XX:XX:XX:XX->FF:FF:FF:FF (-52 dBm): 0x01 ['0xf6', '0x0', '0x1', '0xa7', '0x4c', '0x69', '0x20'] ['0x1', '0xff', '0xff', '0xff', '0xff', '0x34', '0x0'] OrderedDict()
2025-04-10 18:08:47,219 DEBUG: enoceanmqtt/FB/XXXX: PB (Status of the push button)=Released
2025-04-10 18:08:47,219 DEBUG: enoceanmqtt/FB/XXXX: Sent MQTT: {"RSSI": -52, "DATE": "2025-04-10T18:08:47.218875", "RAW_DATA": "00:20", "PB": 0}
2025-04-10 18:08:47,219 DEBUG: Sending PUBLISH (d0, q0, r1, m237), 'b'enoceanmqtt/FB/XXXX'', ... (87 bytes)
2025-04-10 18:08:57,344 DEBUG: XX:XX:XX:XX->FF:FF:FF:FF (-54 dBm): 0x01 ['0xa5', '0x7a', '0x0', '0xf0', '0xf', '0x1', '0xa7', '0x4c', '0x69', '0x0'] ['0x1', '0xff', '0xff', '0xff', '0xff', '0x36', '0x0'] OrderedDict()
2025-04-10 18:08:57,345 DEBUG: enoceanmqtt/Tracker/XXXX: SVC (Supply voltage (OPTIONAL))=2.44 V
2025-04-10 18:08:57,345 DEBUG: enoceanmqtt/Tracker/XXXX: PIRS (PIR Status)=240.0
2025-04-10 18:08:57,345 DEBUG: enoceanmqtt/Tracker/XXXX: SVA (Supply voltage availability)=Supply voltage is supported
2025-04-10 18:08:57,345 DEBUG: enoceanmqtt/Tracker/XXXX: Sent MQTT: {"RSSI": -54, "DATE": "2025-04-10T18:08:57.344563", "RAW_DATA": "7A:00:F0:0F:00", "SVC": 2.44, "PIRS": 240.0, "SVA": 1}
2025-04-10 18:08:57,346 DEBUG: Sending PUBLISH (d0, q0, r1, m238), 'b'enoceanmqtt/Tracker/XXXX'', ... (125 bytes)

But on MQTT Side I get only one Device which has the Values of the device which is configured last in the *.device file with two rssi and two last seen values.

Do you have an idea if it is a part of the enocean or the HA enoceanmqtt code, where the implementation has to be adapted?

Best Regards Stev

**Comment by ChristopheHD** [comment]
Hello,

I think such devices can be implemented by adding a "model" at the end of the [mapping.yaml](https://github.com/ChristopheHD/HA_enoceanmqtt/blob/develop/enoceanmqtt/overlays/homeassistant/mapping.yaml). This will allow you to define a device with multiple EEP and specific entities to it. Then your configuration will be much more simple (`model=eltako/FTTB` instead of EEP configuration).
I can help you to write such configuration but I'm unable to test as I do not have this device. Once it works fine, please share the mapping file so I can add it inside the default configuration and everyone can use it.

Regards

**Reply by Stev-G** [reply]
Hello,

that sounds good. So if I understand it right I Have to adapt the [mapping.yaml](https://github.com/ChristopheHD/HA_enoceanmqtt/blob/develop/enoceanmqtt/overlays/homeassistant/mapping.yaml) (which should not be a problem, because I use a local one) and the *.device file? Could you give me a hint how such a device should be implmented in both files? Would it be similar to the eltako devices e.g. FSB14?

*.device file : 

```
# Define an FTTB device
[my_FTTB ]
address = 0xYYYYYYYY # The address of your FTTB 
model   = eltako/FTTB 
sender  = 0xFFXXXXXX # base id of your EnOcean transceiver + unique offset
```

mapping.yaml : 

```
FTTB : &FTTB 
      device_config:
         - rorg: "0xA5"
           func: "0x07"
           type: "0x01"
           command: ""
           channel: ""
           log_learn: ""
           direction: ""
           answer: ""
         - rorg: "0xF6"
           func: "0x01"
           type: "0x01"
           command: ""
           channel: ""
           log_learn: ""
           direction: ""
           answer: ""
      entities:
        and so on ....
```
      
Testing I can do and also the implmentation. If everything is working find for sure I share the file, that it can be checked in for all other Users. Thanks in Advance!

Best regards Stev

**Reply by ChristopheHD** [reply]
Your understanding is correct and examples you gave are also correct. You are on the right path to implement it!
Feel free to ask question if some points of the configuration are not clear.

**Comment by Stev-G** [comment]
Hello I made the following integration. Regarding the sender I am not sure if I put in the right adress. I use the One which is shown in the mqqt integration for the ENOCEANMQTT device. What do you mean with + unique offset regarding this point?

*.devices : 

```
#Piotec Tracker
[Tracker/XXXX]
address = 0xXXXXXXXX
model   = eltako/v4fttb
sender  = 0xXXXXXXXX
```


mapping.yaml : 

```
v4fttb: &v4fttb
      device_config:
         - rorg: "0xA5"
           func: "0x07"
           type: "0x01"
           command: ""
           channel: ""
           log_learn: ""
           direction: ""
           answer: ""
         - rorg: "0xF6"
           func: "0x01"
           type: "0x01"
           command: ""
           channel: ""
           log_learn: ""
           direction: ""
           answer: ""
      entities:
         - component: "sensor"
           name: "v_raw"
           config:
           state_topic: ""
           value_template: "{{ value_json.SVC }}"
           enabled_by_default: "false"
           availability_topic: ""
           availability_template: >-
             {% if value_json.SVA == 1 %}
               online
             {% else %}
               offline
             {% endif %}
           device_class: "voltage"
           state_class: "measurement"
           unit_of_measurement: "V"
         - component: "sensor"
           name: "voltage"
           config:
              state_topic: ""
              value_template: "{{ value_json.SVC | round(2) }}"
              availability_topic: ""
              availability_template: >-
                {% if value_json.SVA == 1 %}
                  online
                {% else %}
                  offline
                {% endif %}
              device_class: "voltage"
              state_class: "measurement"
              unit_of_measurement: "V"
         - component: binary_sensor
           name: "pir"
           config:
              state_topic: ""
              value_template: >-
                {% if value_json.PIRS >= 128 %}ON{% else %}OFF{% endif %}
              device_class: "occupancy"
         - component: binary_sensor
           name: "button"
           config:
              state_topic: ""
              device_class: "button"
              value_template: "{{ value_json.EB }}"
              payload_on: "1"
              payload_off: "0"
```

In the Protocoll of the Enocean Addon I see the new Device and it would be also published to mqtt. But in the MQTT Integration it is not available as a device. Something I did wrong.

> 2025-04-11 17:32:47,604 DEBUG: XX:XX:XX:XX->FF:FF:FF:FF (-49 dBm): 0x01 ['0xa5', '0x7a', '0x0', '0xf0', '0xf', '0x1', '0xa7', '0x4c', '0x69', '0x0'] ['0x1', '0xff', '0xff', '0xff', '0xff', '0x31', '0x0'] OrderedDict()
> 2025-04-11 17:32:47,605 DEBUG: enoceanmqtt/Tracker/XXXX/a5: SVC (Supply voltage (OPTIONAL))=2.44 V
> 2025-04-11 17:32:47,606 DEBUG: enoceanmqtt/Tracker/XXXX/a5: PIRS (PIR Status)=240.0 
> 2025-04-11 17:32:47,606 DEBUG: enoceanmqtt/Tracker/XXXX/a5: SVA (Supply voltage availability)=Supply voltage is supported 
> 2025-04-11 17:32:47,606 DEBUG: enoceanmqtt/Tracker/XXXX/a5: Sent MQTT: {"_RSSI_": -49, "_DATE_": "2025-04-11T17:32:47.604825", "_RAW_DATA_": "7A:00:F0:0F:00", "SVC": 2.44, "PIRS": 240.0, "SVA": 1}
> 2025-04-11 17:32:47,606 DEBUG: Sending PUBLISH (d0, q0, r1, m251), 'b'enoceanmqtt/Tracker/XXXX/a5'', ... (125 bytes)

> 2025-04-11 17:32:48,196 DEBUG: XX:XX:XX:XX->FF:FF:FF:FF (-49 dBm): 0x01 ['0xf6', '0x70', '0x1', '0xa7', '0x4c', '0x69', '0x30'] ['0x1', '0xff', '0xff', '0xff', '0xff', '0x31', '0x0'] OrderedDict()
> 2025-04-11 17:32:48,197 DEBUG: enoceanmqtt/Tracker/XXXX/f6: PB (Status of the push button)=Pressed 
> 2025-04-11 17:32:48,197 DEBUG: enoceanmqtt/Tracker/XXXX/f6: Sent MQTT: {"_RSSI_": -49, "_DATE_": "2025-04-11T17:32:48.196833", "_RAW_DATA_": "70:30", "PB": 1}
> 2025-04-11 17:32:48,197 DEBUG: Sending PUBLISH (d0, q0, r1, m252), 'b'enoceanmqtt/Tracker/XXXX/f6'', ... (87 bytes)
> 2025-04-11 17:32:48,356 DEBUG: XX:XX:XX:XX->FF:FF:FF:FF (-49 dBm): 0x01 ['0xf6', '0x0', '0x1', '0xa7', '0x4c', '0x69', '0x20'] ['0x1', '0xff', '0xff', '0xff', '0xff', '0x31', '0x0'] OrderedDict()
> 2025-04-11 17:32:48,357 DEBUG: enoceanmqtt/Tracker/XXXX/f6: PB (Status of the push button)=Released 
> 2025-04-11 17:32:48,357 DEBUG: enoceanmqtt/Tracker/XXXX/f6: Sent MQTT: {"_RSSI_": -49, "_DATE_": "2025-04-11T17:32:48.356863", "_RAW_DATA_": "00:20", "PB": 0}
> 2025-04-11 17:32:48,357 DEBUG: Sending PUBLISH (d0, q0, r1, m253), 'b'enoceanmqtt/Tracker/XXXX/f6'', ... (87 bytes)

Do you have any Idea?

**Reply by ChristopheHD** [reply]
You do not need the sender configuration as you will not need to send a command to this device.
Did you previously register a device with the same address ? If yes, I think you need to remove it.

**Comment by Stev-G** [comment]
Hello,

So I had a little bit time at the weekend and I found some mistakes regarding the yaml syntax and I forgot to implment the state topic's. Now it is availaible at mqtt side.

```
#Piotec Tracker
[Tracker/XXXX]
address = 0xXXXXXXXX
model   = eltako/v4fttb
```

```
   v4fttb: &v4fttb
      device_config:
         - rorg: "0xA5"
           func: "0x07"
           type: "0x01"
           command: ""
           channel: ""
           log_learn: ""
           direction: ""
           answer: ""
         - rorg: "0xF6"
           func: "0x01"
           type: "0x01"
           command: ""
           channel: ""
           log_learn: ""
           direction: ""
           answer: ""
      entities:
         - component: "binary_sensor"
           name: "Presence"
           config:
              state_topic: "a5"
              value_template: >-
                {% if value_json.PIRS >= 128 %}
                  ON
                {% else %}
                  OFF
                {% endif %}
              device_class: "presence"
         - component: "sensor"
           name: "v_raw"
           config:
              state_topic: "a5"
              value_template: >- 
                {{ value_json.SVC }}
              enabled_by_default: "false"
              availability_topic: "+"
              availability_template: >-
                {% if value_json.SVA == 1 %}
                  online
                {% else %}
                  offline
                {% endif %}
              device_class: "voltage"
              state_class: "measurement"
              unit_of_measurement: "V"
         - component: "sensor"
           name: "voltage"
           config:
              state_topic: "a5"
              value_template: >- 
                {{ value_json.SVC | round(2) }}
              availability_topic: "+"
              availability_template: >-
                {% if value_json.SVA == 1 %}
                  online
                {% else %}
                  offline
                {% endif %}
              device_class: "voltage"
              state_class: "measurement"
              unit_of_measurement: "V"
         - component: "binary_sensor"
           name: "Button"
           config:
              state_topic: "f6"
              value_template: "{{ value_json.PB }}"
              payload_on: "1"
              payload_off: "0"
```

So the Button, the PIR Value, the rssi and the time stamp would be transmitted now. But not the Voltage  and the raw value of the voltage. I am not so familiar with yaml and the code of the addon. As I found out, the part regarding the models is inside the ha_communicator.py. But it is not easy for me to understand, why these values are available but offline as you can see in the picture.

![image](https://github.com/user-attachments/assets/9e0e69b5-bce4-4d1c-8d3c-2ba603bbe6d8)

Do you have any idea?

**Reply by ChristopheHD** [reply]
Options of YAML entities are described in Home Assistant documentation of MQTT integration.
Supply voltage appeared offline because you have set the availability topic to '+' instead of 'a5'.

**Reply by Stev-G** [reply]
That was the right hint. Thanks a lot. Now it is working as I have it in my mind.

```
   v4fttb: &v4fttb
      device_config:
         - rorg: "0xA5"
           func: "0x07"
           type: "0x01"
           command: ""
           channel: ""
           log_learn: ""
           direction: ""
           answer: ""
         - rorg: "0xF6"
           func: "0x01"
           type: "0x01"
           command: ""
           channel: ""
           log_learn: ""
           direction: ""
           answer: ""
      entities:
         - component: "binary_sensor"
           name: "Presence"
           config:
              state_topic: "a5"
              value_template: >-
                {% if value_json.PIRS >= 128 %}
                  ON
                {% else %}
                  OFF
                {% endif %}
              device_class: "presence"
         - component: "sensor"
           name: "v_raw"
           config:
              state_topic: "a5"
              value_template: >- 
                {{ value_json.SVC }}
              enabled_by_default: "false"
              availability_topic: "a5"
              availability_template: >-
                {% if value_json.SVA == 1 %}
                  online
                {% else %}
                  offline
                {% endif %}
              device_class: "voltage"
              state_class: "measurement"
              unit_of_measurement: "V"
         - component: "sensor"
           name: "voltage"
           config:
              state_topic: "a5"
              value_template: >- 
                {{ value_json.SVC | round(2) }}
              availability_topic: "a5"
              availability_template: >-
                {% if value_json.SVA == 1 %}
                  online
                {% else %}
                  offline
                {% endif %}
              device_class: "voltage"
              state_class: "measurement"
              unit_of_measurement: "V"
         - component: "binary_sensor"
           name: "Button"
           config:
              state_topic: "f6"
              value_template: "{{ value_json.PB }}"
              payload_on: "1"
              payload_off: "0"
```

![image](https://github.com/user-attachments/assets/c66a50cf-283a-4bc1-a0d5-db254c9883f9)

Many Thanks. If somebody will also use it, above is the model implmentation. Now I will take a look to change the Presence state if the telegram is not coming anymore (outside of home). Maybe with set state via automation or do you think it is possible to implement such a thing at addon side?

**Reply by ChristopheHD** [reply]
Yes it can be implemeted via the addon, you can use off_delay yaml option as described here: https://www.home-assistant.io/integrations/binary_sensor.mqtt/

**Reply by ChristopheHD** [reply]
Did you manage to set the off delay option ? If yes, can you share your final mapping so I can put it in the code and make it available for everyone ?

**Reply by Stev-G** [reply]
Hi Christophe,

sorry for my late response. I had so much to do the last time, that I was not able to do anything regarding the implmentation. But today I tested with the implmentation of the off_delay option an it works fine. For me 60s was ok. Maybe if the user has a different implmentation e.g ping every 2minutes, than this value has to be adapted.

```
v4fttb: &v4fttb
      device_config:
         - rorg: "0xA5"
           func: "0x07"
           type: "0x01"
           command: ""
           channel: ""
           log_learn: ""
           direction: ""
           answer: ""
         - rorg: "0xF6"
           func: "0x01"
           type: "0x01"
           command: ""
           channel: ""
           log_learn: ""
           direction: ""
           answer: ""
      entities:
         - component: "binary_sensor"
           name: "Presence"
           config:
              state_topic: "a5"
              value_template: >-
                {% if value_json.PIRS >= 128 %}
                  ON
                {% else %}
                  OFF
                {% endif %}
              device_class: "presence"
              off_delay: 60
         - component: "sensor"
           name: "v_raw"
           config:
              state_topic: "a5"
              value_template: >- 
                {{ value_json.SVC }}
              enabled_by_default: "false"
              availability_topic: "a5"
              availability_template: >-
                {% if value_json.SVA == 1 %}
                  online
                {% else %}
                  offline
                {% endif %}
              device_class: "voltage"
              state_class: "measurement"
              unit_of_measurement: "V"
         - component: "sensor"
           name: "voltage"
           config:
              state_topic: "a5"
              value_template: >- 
                {{ value_json.SVC | round(2) }}
              availability_topic: "a5"
              availability_template: >-
                {% if value_json.SVA == 1 %}
                  online
                {% else %}
                  offline
                {% endif %}
              device_class: "voltage"
              state_class: "measurement"
              unit_of_measurement: "V"
         - component: "binary_sensor"
           name: "Button"
           config:
              state_topic: "f6"
              value_template: "{{ value_json.PB }}"
              payload_on: "1"
              payload_off: "0"
```
