### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by TeggolT** [ChristopheHD/HA_enoceanmqtt-addon#17]
I can give anyone who wants them logs, or configs, but all I really need to tell you is: It works on the virtualbox-vm. I made a backup and installed it onto a raspi. It doesn't work there.
It, in this case, is being able to send packets using ha_enoceanmqtt. On the pi, it works, but only somewhat: It does send the addresses I configured, but the OrderedDict, which contains switch data and position, is shown in the logs as empty.
If you have any ideas, please tell me.

Thanks for reading.

**Comment by ChristopheHD** [comment]
Can you indicate which device you are trying to use and the configuration you put in place ?

**Comment by TeggolT** [comment]
sure. I have a USB300 and I am creating virtual switches to toggle the fsr14-4x (and FAM14) eltako modules as detailed in [this guide.](https://github.com/mak-gitdev/HA_enoceanmqtt/wiki/Using-virtual-buttons-with-Eltako-FAM14)

My addition to configuration.mqtt is this, most of it is copypasted.
```
switch:
  - platform: template
    switches:
      zentral:
        friendly_name: Zentral Ein/Aus
        value_template: "{{ is_state('select.e2m_relay_zentral_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_zentral_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_zentral_action
            data:
              option: AI

      timon:
        friendly_name: Timon licht
        value_template: "{{ is_state('select.e2m_relay_timon_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_timon_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_timon_action
            data:
              option: AI

      hannah:
        friendly_name: Hannah licht
        value_template: "{{ is_state('select.e2m_relay_hannah_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_hannah_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_hannah_action
            data:
              option: AI

      kammer:
        friendly_name: Spielekammer licht
        value_template: "{{ is_state('select.e2m_relay_kammer_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_kammer_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_kammer_action
            data:
              option: AI

      schlafen:
        friendly_name: Schlafzimmer licht
        value_template: "{{ is_state('select.e2m_relay_schlafen_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_schlafen_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_schlafen_action
            data:
              option: AI

      grossesbad:
        friendly_name: Bad Licht
        value_template: "{{ is_state('select.e2m_relay_grossesbad_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_grossesbad_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_grossesbad_action
            data:
              option: AI
      grossesbadspiegel:
        friendly_name: Bad Spiegellicht
        value_template: "{{ is_state('select.e2m_relay_grossesbadspiegel_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_grossesbadspiegel_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_grossesbadspiegel_action
            data:
              option: AI

      fluroben:
        friendly_name: Flurlicht oben
        value_template: "{{ is_state('select.e2m_relay_fluroben_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_fluroben_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_fluroben_action
            data:
              option: AI

      treppe:
        friendly_name: Treppenlicht
        value_template: "{{ is_state('select.e2m_relay_treppe_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_treppe_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_treppe_action
            data:
              option: AI

      flurunten:
        friendly_name: Flurlicht Unten
        value_template: "{{ is_state('select.e2m_relay_flurunten_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_flurunten_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_flurunten_action
            data:
              option: AI

      trslinks:
        friendly_name: Terassenlicht links
        value_template: "{{ is_state('select.e2m_relay_trslinks_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_trslinks_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_trslinks_action
            data:
              option: AI

      trsrechts:
        friendly_name: Terassenlicht rechts
        value_template: "{{ is_state('select.e2m_relay_trsrechts_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_trsrechts_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_trsrechts_action
            data:
              option: AI
      kueche:
        friendly_name: Küchenlicht
        value_template: "{{ is_state('select.e2m_relay_kueche_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_kueche_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_kueche_action
            data:
              option: AI
      essen:
        friendly_name: Wintergartenlicht
        value_template: "{{ is_state('select.e2m_relay_essen_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_essen_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_essen_action
            data:
              option: AI
      wohnen:
        friendly_name: Wohnzimmerlicht
        value_template: "{{ is_state('select.e2m_relay_wohnen_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_wohnen_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_wohnen_action
            data:
              option: AI
      badgast:
        friendly_name: Gäste-WC-Licht
        value_template: "{{ is_state('select.e2m_relay_badgast_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_badgast_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_badgast_action
            data:
              option: AI
      arbeiten:
        friendly_name: Arbeitszimmerlicht
        value_template: "{{ is_state('select.e2m_relay_arbeiten_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_arbeiten_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_arbeiten_action
            data:
              option: AI
      technik:
        friendly_name: Technikraumlicht
        value_template: "{{ is_state('select.e2m_relay_technik_action', 'AO') }}"
        turn_on:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_technik_action
            data:
              option: AO
        turn_off:
          - service: select.select_option
            target:
              entity_id: select.e2m_relay_technik_action
            data:
              option: AI

```
Notably, the relay_state entities didn't work, so I'm currently using the state that was last selected in haos. It's not a fix but good enough.

I have set these devices up in ha_enoceanmqtt.devices and they appear in haos:
```
[relay_state/zentral]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/zentral]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E4FF
virtual 		= 1

[relay_state/timon]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/timon]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E491
virtual 		= 1

[relay_state/hannah]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/hannah]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E492
virtual 		= 1

[relay_state/kammer]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/kammer]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E493
virtual 		= 1

[relay_state/schlafen]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/schlafen]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E490
virtual 		= 1

[relay_state/grossesbad]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/grossesbad]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E48E
virtual 		= 1

[relay_state/grossesbadspiegel]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/grossesbadspiegel]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E48F
virtual 		= 1

[relay_state/treppe]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/treppe]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E48D
virtual 		= 1

[relay_state/fluroben]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/fluroben]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E48C
virtual 		= 1

[relay_state/flurunten]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/flurunten]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E480
virtual 		= 1

[relay_state/trslinks]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/trslinks]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E481
virtual 		= 1

[relay_state/trsrechts]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/trsrechts]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E482
virtual 		= 1

[relay_state/kueche]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/kueche]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E484
virtual 		= 1

[relay_state/essen]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/essen]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E485
virtual 		= 1

[relay_state/wohnen]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/wohnen]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E486
virtual 		= 1

[relay_state/badgast]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/badgast]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E488
virtual 		= 1

[relay_state/arbeiten]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/arbeiten]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E489
virtual 		= 1

[relay_state/technik]
address 		= 0x003CEA19
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01

[relay/technik]
address 		= 0xFFFFFFFF
rorg    		= 0xF6
func    		= 0x02
type    		= 0x01
sender  		= 0xFFA6E48A
virtual 		= 1
```
the issue with the relay states is probably that I have no idea what address to use. I've picked this one up from the logs while pressing a physical switch, but I've also tried 0xFFFFFFFF and the sender address 0xFFA6E480.

However, my primary issue is that the integration is not sending switch data, only the sender and address i configured here.

```
2025-02-16 15:59:59,654 INFO: sending: FF:A6:E4:89->FF:FF:FF:FF (-255 dBm): 0x01 ['0xf6', '0x0', '0xff', '0xa6', '0xe4', '0x89', '0x0'] ['0x3', '0xff', '0xff', '0xff', '0xff', '0xff', '0x0'] OrderedDict()
2025-02-16 15:59:59,698 INFO: Sending packet
2025-02-16 15:59:59,800 INFO: got response packet: OK

```

Again, the weirdest thing about this is that the empty OrderedDict is the only visible difference between the raspi and vm. No error messages, no nothing. It kinda makes me reject any idea i have to try and fix it.

Also, thanks for responding this quickly. I've made issues in the discord and in git-makdevs "original" repository, but these all seem to be dead. It's nice to see  at least a little bit of activity in this niche space.
